shell = {program = "/bin/zsh", args = ["-l"]}

live_config_reload = true
ipc_socket = true

[window]
opacity = 0.5
padding = {x = 10, y = 10}
blur = true

[scrolling]
multiplier = 5

[font]
normal = {family = "IntelOne Mono", style = "Regular"}
bold = {family = "IntelOne Mono", style = "Bold"}
italic = {family = "IntelOne Mono", style = "Italic"}
bold_italic = {family = "IntelOne Mono", style = "Bold Italic"}
size = 10
builtin_box_drawing = true

[colors]
[colors.primary]
foreground = "#FBF1C7"
background = "#1D2021"

[colors.cursor]
text = "#FB4934" # red
cursor = "#FB4934" # red

[colors.vi_mode_cursor]
text = "#FB4934" # red
cursor = "#FB4934" # red

[colors.search]
matches = {foreground = "#83A598", background = "CellBackground"}
focused_match = {foreground = "#83A598", background = "CellBackground"}

[colors.normal]
black = "#282828"
red = "#FB4934"
green = "#B8BB26"
yellow = "#FABD2F"
blue = "#83A598"
magenta = "#D3869B"
cyan = "#689D6A"
white = "#FBF1C7"

[colors.bright]
black = "#1D2021"
red = "#CC341D"
green = "#98971A"
yellow = "#D79921"
blue = "#458588"
magenta = "#B16286"
cyan = "#689D6A"
white = "#EBDBB2"

[selection]
save_to_clipboard = true

[cursor]
[cursor.style]
shape = "Block"
blinking = "Never"

[cursor.vi_mode_style]
shape = "Block"
blinking = "Never"

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
  {key = 'Enter', mods = 'SHIFT', action = 'ToggleViMode'},
  {key = 'Y', mods = 'CONTROL', action = 'Copy'},
  {key = 'P', mods = 'CONTROL', action = 'Paste'},
  {key = 'Space', mods = 'SHIFT', action = 'CreateNewTab'},
]
